export const GET_BOOK_REQUEST="GET_BOOK_REQUEST"
export const GET_BOOK_SUCESS="GET_BOOK_SUCESS"
export const GET_BOOK_FAILURE="GET_BOOK_FAILURE"

export const POST_BOOK_REQUEST="POST_BOOK_REQUEST"
export const POST_BOOK_SUCESS="POST_BOOK_SUCESS"
export const POST_BOOK_FAILURE="POST_BOOK_FAILURE"

export const EDIT_BOOK_REQUEST="EDIT_BOOK_REQUEST"
export const EDIT_BOOK_SUCESS="EDIT_BOOK_SUCESS"
export const EDIT_BOOK_FAILURE="EDIT_BOOK_FAILURE"

export const DELETE_BOOK_REQUEST="DELETE_BOOK_REQUEST"
export const DELETE_BOOK_SUCESS="DELETE_BOOK_SUCESS"
export const DELETE_BOOK_FAILURE="DELETE_BOOK_FAILURE"

